### ISSUE TITLE
Is it possible to generate a tlb file for net8.0 with a net48 reference?

### ISSUE THREAD

**Issue by Jepsens1** [dspace-group/dscom#296] opened 2024-11-18 13:38 UTC
Hi

Is it possible to generate a type library file for net8.0 project that has a net48 reference? 

I tried adding package reference to dSpace build task and enabled com hosting
![image](https://github.com/user-attachments/assets/e2ff0263-f735-4a50-8307-ee75e967eaf7)

The class looks like this 
![image](https://github.com/user-attachments/assets/54c0edd1-8eff-48b0-9809-e68c922d7945)

Sadly during rebuild the following message is shown: `Failed to export type library. Failed to set GUID for xxx. Duplicate ID in inheritance hierarchy. (0x800288C6 (TYPE_E_DUPLICATEID))`

I have a prebuild event that takes a dll and generated a new dll as shown
`  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="C:\Windows\System32\regsvr32 /s $(PkgDir)\lib\net48\ModuleServer.dll&#xD;&#xA;&quot;$(TargetFrameworkSDKToolsDirectory)tlbimp&quot; $(PkgDir)\lib\net48\ModuleServer.dll /namespace:ModuleServer /delaysign /keyfile:$(SolutionDir)..\Pair.snk /out:$(TargetDir)Interop.ModuleServer.dll&#xD;&#xA;&quot;$(TargetFrameworkSDKToolsDirectory)sn&quot; -R $(TargetDir)Interop.ModuleServer.dll $(SolutionDir)..\Pair.snk" />
  </Target>`

![image](https://github.com/user-attachments/assets/54939de8-8f3a-4aa4-b255-6b1b628a8bf2)
Looking at dotpeek the referenced dll is using mscorlib, so is it possible to generate a tlb for net8.0 using net48 references? Can i be solved with an adapter or am i required to make reference net8.0

**Comment by electro-logic** [comment] 2024-11-18 16:14
Is ModuleServer.IAction marked with [ComVisible]?

**Comment by Jepsens1** [comment] 2024-11-18 16:48
No, it has `[Guid], [TypeLibType(TpyeLibTypeFlags.FDual | TypeLibTypeFlags.FDispatchable)] and [ComImport]`

To give a bit more background story, this project was previously net48 only and used regasm in a postbuild event. Now it targets both net48 and net8.0 and uses regasm for net48 and dscom build task when using net8.0.

I have tried to only use dscom for both frameworks but im getting following error for both frameworks: `Failed to export type library. Failed to set GUID for ModuleServer. Duplicate ID in inheritance hierarchy. (0x800288C6 (TYPE_E_DUPLICATEID))`. It does seem like i have any duplicate guids in the code atleast

**Comment by SOsterbrink** [comment] 2024-11-19 08:08
I think your project will fail to export if you require the Net Framework 4.8 mscorelib in an .NET 8 context. 
My guess in this situation is that the .NET 8 project uses the mscorelib from .NET 8 and your Interop.ModuleServer.dll references the same library from .NET Framework 4.8. If I remember correctly, the both versions of the library contain the same types with the same GUIDs but with slightly different implementations.   
This leads to the mentioned error message that you have duplicate IDs because some types with the same GUIDs are imported twice. 

A possible workaround could be to generate the tlb file for the  Interop.ModuleServer.dll separately and then to use the tlb reference in the .NET 8 project and not the Interop library. 

I would have to do some experiments to verify my guesses but I will not find the time for this today and likely not this week  :(

**Comment by Jepsens1** [comment] 2024-11-19 08:50
Thanks for the possible suggested workaround, I tried to run `tlbexport Interop.ModuleServer.dll` but received same duplicate IDs error message. Looking at Interop.ModuleServer.dll in dotpeek, it's actually a net40 dll with reference to mscorlib, and the dll i am trying to export to tlb is having the Interop.ModuleServer.dll as reference and System.Runtime which has System.Private.CoreLib. So as you point out that there is a clash between mscorelib and System.Private.Corelib.

So i guess my solutions are
1. Make the interop.moduleserver net8.0
2. Make an adapter using the adapter pattern(might still clash with mscorlib)

**Comment by electro-logic** [comment] 2024-11-19 09:14
> No, it has `[Guid]` `[TypeLibType(TypeLibTypeFlags.FDual | TypeLibTypeFlags.FDispatchable)]` and `[ComImport]`
> 
> To give a bit more background story, this project was previously net48 only and used regasm in a postbuild event. Now it targets both net48 and net8.0 and uses regasm for net48 and dscom build task when using net8.0.
> 
> I have tried to only use dscom for both frameworks but im getting following error for both frameworks: `Failed to export type library. Failed to set GUID for ModuleServer. Duplicate ID in inheritance hierarchy. (0x800288C6 (TYPE_E_DUPLICATEID))`. It does not seem like i have any duplicate guids in the code at least

If IAction is a COM interface, would be easier to have it in the .NET 8 assembly only, and have it as a .NET interface in the .NET 4.8 assembly.

**Comment by Jepsens1** [comment] 2024-11-19 10:36
Problem is that the IAction and the dll is coming from a third party, so its going to be net40 until its updated from their end. So im kinda running out of options

**Comment by electro-logic** [comment] 2024-11-19 10:52
A workaround can be to duplicate IAction in your assembly and use the "local" version

**Comment by marklechtermann** [comment] 2024-11-19 16:34
> I tried to run `tlbexport Interop.ModuleServer.dll` but received same duplicate IDs error message.

Do I understand correctly that `Interop.ModuleServer.dll` is the .NET 4.8 assembly?
If `tlbexport Interop.ModuleServer.dll` returns the same error, then I'm afraid dscom won't be able to help you either.  
The error is rather that two interfaces or classes have the same GUID in the `Interop.ModuleServer.dll`

**Comment by carstencodes** [comment] 2024-11-20 08:56
@Jepsens1 this can easily be checked with Powershell

```powershell
$assembly = [System.Reflection.Assembly]::LoadFrom($AssemblyFilePath)
$types = $assembly.GetTypes();
$guids = @{}

foreach ($type in $types)
{
    foreach ($attr in [System.Reflection.Assembly]::GetAttributes($type))
   {
       if ($attr -is [System.Runtime.InteropServices.GuidAttribute])
       {
            îf (-not $guids.ContainsKey($attr.Value))
            {
                  $guid[attr.Value] = $type.FullName;
            }
            else
            {
                  Write-Error "Guid $attr.Value is already taken by $guids[$attr.Value] and cannot be used by $type.FullName";
            }
       }
   }
}
```

**Comment by SOsterbrink** [comment] 2024-11-20 15:14
If the problem is located in the Interop library we can close this issue, because dscom will not be able to fix a broken 3rd party library.  
Please correct me if I am wrong about that @Jepsens1

**Closed by SOsterbrink** 2024-11-20 15:14 UTC
Labels: question
